-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- Step 1: Adds all 62 organized columns (already done if you ran this before)
-- Step 2: Drops the now-redundant full_data JSONB column
-- Safe to run multiple times (uses IF NOT EXISTS / IF EXISTS)

ALTER TABLE organized_trials
  ADD COLUMN IF NOT EXISTS other_ids                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS acronym                          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS org_full_name                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS status_verified_date             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS exclusion_rationale              TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS expanded_access_info             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS start_date_type                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_completion_date_type     TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS completion_date                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS completion_date_type             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS study_first_submit_date          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS study_first_submit_qc_date       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS study_first_post_date_type       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_update_submit_date          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_update_post_date_type       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS sponsors                         TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS collaborators                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS funder_type                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS responsible_party_type           TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS responsible_party_lead_sponsor   TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS responsible_party_lead_sponsor_class TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS fda_regulated_drug               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS fda_regulated_device             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS has_dmc                          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS brief_summary                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS detailed_description             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS study_type                       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS phases                           TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS allocation                       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS intervention_model               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS masking                          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_purpose                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS enrollment_type                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_outcomes                 TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS secondary_outcomes               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS eligibility_criteria             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS sex                              TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS minimum_age                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS standard_ages                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS healthy_volunteers               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS central_contacts                 TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS overall_officials                TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS locations                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS study_documents                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS reference_count                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS pmids                            TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS citations                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS ipd_sharing                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS mesh_conditions                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS mesh_interventions               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_drug                     TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS parsed_date                      TEXT DEFAULT '';
