-- rebuild_schema.sql
-- Run in Supabase SQL Editor (Dashboard → SQL Editor → New query).
-- Drops ALL old named columns (original 15 + 52 snake_case) and replaces them
-- with the exact ORGANIZED_COLS names from parse_study_to_organized().
-- Safe to re-run: uses IF EXISTS / IF NOT EXISTS throughout.
-- After running this, execute: python reparse_all.py ADC

-- ── Step 1: Drop all old named columns ─────────────────────────────────────────
ALTER TABLE organized_trials
  DROP COLUMN IF EXISTS full_data,
  DROP COLUMN IF EXISTS study_url,
  DROP COLUMN IF EXISTS brief_title,
  DROP COLUMN IF EXISTS official_title,
  DROP COLUMN IF EXISTS overall_status,
  DROP COLUMN IF EXISTS phase,
  DROP COLUMN IF EXISTS enrollment,
  DROP COLUMN IF EXISTS lead_sponsor,
  DROP COLUMN IF EXISTS conditions,
  DROP COLUMN IF EXISTS interventions,
  DROP COLUMN IF EXISTS start_date,
  DROP COLUMN IF EXISTS primary_completion_date,
  DROP COLUMN IF EXISTS last_update_post_date,
  DROP COLUMN IF EXISTS study_first_post_date,
  DROP COLUMN IF EXISTS other_ids,
  DROP COLUMN IF EXISTS acronym,
  DROP COLUMN IF EXISTS org_full_name,
  DROP COLUMN IF EXISTS status_verified_date,
  DROP COLUMN IF EXISTS exclusion_rationale,
  DROP COLUMN IF EXISTS expanded_access_info,
  DROP COLUMN IF EXISTS start_date_type,
  DROP COLUMN IF EXISTS primary_completion_date_type,
  DROP COLUMN IF EXISTS completion_date,
  DROP COLUMN IF EXISTS completion_date_type,
  DROP COLUMN IF EXISTS study_first_submit_date,
  DROP COLUMN IF EXISTS study_first_submit_qc_date,
  DROP COLUMN IF EXISTS study_first_post_date_type,
  DROP COLUMN IF EXISTS last_update_submit_date,
  DROP COLUMN IF EXISTS last_update_post_date_type,
  DROP COLUMN IF EXISTS sponsors,
  DROP COLUMN IF EXISTS collaborators,
  DROP COLUMN IF EXISTS funder_type,
  DROP COLUMN IF EXISTS responsible_party_type,
  DROP COLUMN IF EXISTS responsible_party_lead_sponsor,
  DROP COLUMN IF EXISTS responsible_party_lead_sponsor_class,
  DROP COLUMN IF EXISTS fda_regulated_drug,
  DROP COLUMN IF EXISTS fda_regulated_device,
  DROP COLUMN IF EXISTS has_dmc,
  DROP COLUMN IF EXISTS brief_summary,
  DROP COLUMN IF EXISTS detailed_description,
  DROP COLUMN IF EXISTS study_type,
  DROP COLUMN IF EXISTS phases,
  DROP COLUMN IF EXISTS allocation,
  DROP COLUMN IF EXISTS intervention_model,
  DROP COLUMN IF EXISTS masking,
  DROP COLUMN IF EXISTS primary_purpose,
  DROP COLUMN IF EXISTS enrollment_type,
  DROP COLUMN IF EXISTS primary_outcomes,
  DROP COLUMN IF EXISTS secondary_outcomes,
  DROP COLUMN IF EXISTS eligibility_criteria,
  DROP COLUMN IF EXISTS sex,
  DROP COLUMN IF EXISTS minimum_age,
  DROP COLUMN IF EXISTS standard_ages,
  DROP COLUMN IF EXISTS healthy_volunteers,
  DROP COLUMN IF EXISTS central_contacts,
  DROP COLUMN IF EXISTS overall_officials,
  DROP COLUMN IF EXISTS locations,
  DROP COLUMN IF EXISTS study_documents,
  DROP COLUMN IF EXISTS reference_count,
  DROP COLUMN IF EXISTS pmids,
  DROP COLUMN IF EXISTS citations,
  DROP COLUMN IF EXISTS ipd_sharing,
  DROP COLUMN IF EXISTS mesh_conditions,
  DROP COLUMN IF EXISTS mesh_interventions,
  DROP COLUMN IF EXISTS primary_drug,
  DROP COLUMN IF EXISTS parsed_date;

-- ── Step 2: Add exact ORGANIZED_COLS columns ────────────────────────────────────
ALTER TABLE organized_trials
  ADD COLUMN IF NOT EXISTS "Study URL"                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Other IDs"                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Brief Title"                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Official Title"                   TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Acronym"                          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Org Full Name"                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Overall Status"                   TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Status Verified Date"             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Exclusion Rationale"              TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Expanded Access Info"             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Start Date"                       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Start DateType"                   TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Primary Completion Date"          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Primary Completion DateType"      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "completionDateStructDate"         TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "completionDateStructType"         TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "studyFirstSubmitDate"             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "studyFirstSubmitQcDate"           TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Study First Post Date"            TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "studyFirstPostDateType"           TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Last Update Submit Date"          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Last Update Post Date"            TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "lastUpdatePostDateType"           TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Sponsors"                         TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Collaborators"                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Funder Type"                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "responsiblePartyType"             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "responsiblePartyleadSponsor"      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "responsiblePartyleadSponsorclass" TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "FDA Regulated Drug"               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "FDA Regulated Device"             TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Has DMC"                          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "briefSummary"                     TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "detailedDescription"              TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "conditions"                       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "studyType"                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "phases"                           TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Allocation"                       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Intervention Model"               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Masking"                          TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Primary Purpose"                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Enrollment"                       TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "enrollmentInfoType"               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Interventions"                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Primary Outcomes"                 TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Secondary Outcomes"               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "eligibilityCriteria"              TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Sex"                              TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Minimum Age"                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Standard Ages"                    TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "healthyVolunteers"                TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Central Contacts"                 TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Overall Officials"                TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Locations"                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Study Documents"                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Reference Count"                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "PMIDs"                            TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Citations"                        TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "IPD Sharing"                      TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "MeSH Conditions"                  TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "MeSH Interventions"               TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Primary Drug"                     TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS "_parsed_date"                     TEXT DEFAULT '';

-- ── Step 3: Rebuild indexes on new column names ────────────────────────────────
DROP INDEX IF EXISTS idx_organized_status;
DROP INDEX IF EXISTS idx_organized_phase;
DROP INDEX IF EXISTS idx_organized_sponsor;

CREATE INDEX idx_organized_status  ON public.organized_trials ("Overall Status");
CREATE INDEX idx_organized_phase   ON public.organized_trials ("phases");
CREATE INDEX idx_organized_sponsor ON public.organized_trials ("Sponsors");
